In [1]:
## dependecies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import json
import gmaps
import os
from pprint import pprint

# Import API Key
from vaca_config import go_key

In [2]:
## import csv file from Output folder and display
city_weather_df = pd.read_csv('../Output/weather_data.csv')
city_weather_df.head()

,City,Lat,Long,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,dingle,10.9995,122.6711,81.64,83.0,91.0,6.33,PH,1.615609e+09
1,busselton,-33.6500,115.3333,70.00,49.0,0.0,3.00,AU,1.615609e+09
2,guerrero negro,27.9769,-114.0611,55.56,64.0,0.0,12.77,MX,1.615609e+09
3,bluff,-46.6000,168.3333,64.99,71.0,0.0,5.99,NZ,1.615609e+09
4,bredasdorp,-34.5322,20.0403,51.80,93.0,45.0,1.14,ZA,1.615609e+09

In [3]:
## initialize and configure gmaps with api key
gmaps.configure(api_key=go_key)

In [11]:
## set variables for Heat map
locations = city_weather_df[['Lat','Long']].astype(float)
city_humidity = city_weather_df['Humidity']

## initialize google map figure for heat map
fig = gmaps.figure()

## define heat map layer using humidity
heat_humidity = gmaps.heatmap_layer(locations, weights=city_humidity,
                                    max_intensity=50)

## Add heat may layer
fig.add_layer(heat_humidity)

## Show figure
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
## Define the parameters for the ideal vacation spots
ideal_locations_df = city_weather_df.loc[(city_weather_df['Max Temp']>=70)&
                                         (city_weather_df['Max Temp']<=80)&
                                         (city_weather_df['Wind Speed']<=10)&
                                         (city_weather_df['Cloudiness']==0)]

## add a blank column for hotel names for ideal location spots
ideal_locations_df['Hotel'] = ''

<ipython-input-5-e9f1c6641316>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ideal_locations_df['Hotel'] = ''

In [6]:
## define base url for google places api
base_url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?locations='

## define the paramaters for the google places api request
params = {'location':'',
         'radius':5000,
         'type':'hotel',
         'key':go_key}

## for loop through city name to get nearest hotel and name to display in dataframe
for index, row in ideal_locations_df.iterrows():
    params['location'] = str(row['Lat']) + ',' + str(row['Long'])
    response = requests.get(base_url, params=params).json()
    
    ideal_locations_df.loc[index, 'Hotel'] = response['results'][1]['name']

/Users/garrettgomez/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [7]:
## display data frame for ideal vacation spots with first hotel name
ideal_locations_df

,City,Lat,Long,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel
1,busselton,-33.6500,115.3333,70.00,49.0,0.0,3.00,AU,1.615609e+09,Observatory Guest House
42,tahoua,14.8888,5.2692,77.00,19.0,0.0,2.30,NE,1.615609e+09,BOA Tahoua
69,itupiranga,-5.1347,-49.3267,75.20,100.0,0.0,2.19,BR,1.615609e+09,Mun Itupiranga Hall
71,nioro,13.3500,-15.7500,71.60,14.0,0.0,6.82,GM,1.615609e+09,Madina Mosque
97,east london,-33.0153,27.9116,75.20,73.0,0.0,8.05,ZA,1.615609e+09,Tu Casa
103,coahuayana,18.7333,-103.6833,70.39,70.0,0.0,3.22,MX,1.615609e+09,Chonita Bananas
200,pochutla,15.7432,-96.4661,79.00,69.0,0.0,3.78,MX,1.615609e+09,Hotel Posada San Jose
239,caravelas,-17.7125,-39.2481,72.36,82.0,0.0,4.88,BR,1.615609e+09,Conselho Tutelar
279,oussouye,12.4850,-16.5469,73.40,73.0,0.0,2.30,SN,1.615609e+09,Asamblea de Cooperacion por la Paz (Senegal)
298,cidreira,-30.1811,-50.2056,70.48,79.0,0.0,6.04,BR,1.615609e+09,Diego Imóveis
314,barranca,-10.7500,-77.7667,70.20,88.0,0.0,4.76,PE,1.615609e+09,El Olivar Hospedaje
337,huarmey,-10.0681,-78.1522,72.36,81.0,0.0,6.49,PE,1.615609e+09,Hotel Miramar
397,mecca,21.4267,39.8261,73.45,49.0,0.0,4.94,SA,1.615609e+09,"Makkah Clock Royal Tower, A Fairmont Hotel"
412,hualmay,-11.0964,-77.6139,71.29,86.0,0.0,6.67,PE,1.615609e+09,Alas Peruanas University
426,miandrivazo,-19.5167,45.4667,76.77,78.0,0.0,4.36,MG,1.615609e+09,Hôtel Arc En Ciel Miandrivazo
471,waounde,15.2637,-12.8682,77.00,29.0,0.0,9.22,SN,1.615609e+09,Primary School De Waounde

In [8]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in ideal_locations_df.iterrows()]
locations = ideal_locations_df[["Lat", "Long"]]

In [9]:
## create markers with hotel name, city and country
markers = gmaps.marker_layer(locations,info_box_content=hotel_info)
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))